version: '2'

services:
  webserver:
    build: './webserver'
    ports:
      - 80:80
      - 443:443
      - 3306:3306
    volumes:
      - ./www:/var/www
    #external_host:
    extra_hosts:
      - local:0.0.0.0